version: '3'
services:
    app:
        image: ${COMPOSE_PROJECT_NAME}/app
        build: ./services/app
        command: yarn serve
        volumes:
            - ../..:/code
        ports:
            - ${APP_PORT}:8080
